---
# Install Java runtime
- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install OpenJDK 17
  apt:
    name: openjdk-17-jdk
    state: present

- name: Set JAVA_HOME environment variable
  lineinfile:
    path: /etc/environment
    line: 'JAVA_HOME="/usr/lib/jvm/java-17-openjdk-amd64"'
    state: present

- name: Verify Java installation
  command: java -version
  register: java_version
  failed_when: false

- name: Display Java version
  debug:
    var: java_version.stderr
